### ISSUE TITLE
Create dotcom shell template

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm.com-design-kit#23]
## Detailed description

Carbon provides a ui shell template to help designers see how the ui shell should work at different breakpoints, how the right and left panels look when expanded, and how the different pieces work with the grid.
[Link to ui shell template](https://sketch.cloud/s/EjVmA)

We should provide a similar template to help designers with their responsive designs. Things to include:

**L0 + default footer**
- [x] max 
- [x] xlg
- [x] lg - left panel closed
- [x] lg - left panel open
- [x] med- left panel closed
- [x] med- left panel open
- [x] sm- left panel closed
- [x] sm- left panel closed

**L0 + L1 + default footer**
- [x] max
- [x] xlg
- [x] lg - left panel closed
- [x] lg - left panel open
- [x] med- left panel closed
- [x] med- left panel open
- [x] sm- left panel closed
- [x] sm- left panel closed

## Acceptance criteria
- [ ] template reviewed by design
- [ ] template approved by Wonil
- [ ] template added to Box folder

**Comment by oliviaflory** [comment]
<img width="1925" alt="Screen Shot 2019-12-03 at 5 38 22 PM" src="https://user-images.githubusercontent.com/45692622/70095993-0945e300-15f4-11ea-8b6c-123d1f02f850.png">
@larahanlon2 

I'm working on the L0 & L1 mock ups for the Dotcom shell template, and wanted to confirm that Option 2 is the desired behavior for the open state on medium and small breakpoint?

**Option 1**
- L1 is _above_ the overlay
- the side menu is flush to the L0


**Option 2**
- L1 is *below* the overlay
- the side menu is flush to the L0

**Comment by oliviaflory** [comment]
@wonilsuhibm @larahanlon2 

Please review the Dotcom shell template sketch file: https://ibm.ent.box.com/file/570389656421
The goal of this document is to show designers how the masthead and footer behave at different breakpoints.
<img width="1993" alt="Screen Shot 2019-12-04 at 11 58 02 AM" src="https://user-images.githubusercontent.com/45692622/70165289-a5252c80-1690-11ea-977a-91b5c18f28d6.png">




**A few things I'd like your take on:**

1. Question from above, is the expected behavior of the side menu at small breakpoints is for the L1 to be _below_ the overlay (Option 2)?
<img width="1925" alt="Screen Shot 2019-12-03 at 5 38 22 PM" src="https://user-images.githubusercontent.com/45692622/70164841-e79a3980-168f-11ea-97a9-e8d7256b0cf0.png">

2. Is it clear in these examples that the side menu is corresponding to the L1 menu items and _not_ the L0 menu items? Would it be more clear to label it something different like `Sub link 1`?

<img width="1359" alt="Screen Shot 2019-12-04 at 12 10 20 PM" src="https://user-images.githubusercontent.com/45692622/70165197-7c049c00-1690-11ea-9faf-f92f7b0b3b89.png">

3. Should we include the **Short footer** in this template? I originally thought to exclude it because we don't want to encourage teams to use the short version.


---

For reference this is what [Carbon's UI shell template](https://sketch.cloud/s/EjVmA) looks like
<img width="2004" alt="Screen Shot 2019-12-04 at 12 02 48 PM" src="https://user-images.githubusercontent.com/45692622/70163828-157e7e80-168e-11ea-8575-563cb7633590.png">

**Comment by larahanlon2** [comment]
1. At small breakpoints (672 and below) the only L1 thing that shows is the title. All nav _links_ roll up into the hamburger. L0 and L1 inclusive.

<img width="742" alt="Screen Shot 2019-12-05 at 4 55 55 PM" src="https://user-images.githubusercontent.com/53093550/70277652-c9603680-1780-11ea-868a-6ac8176509bf.png">
<img width="1519" alt="Screen Shot 2019-12-05 at 4 57 30 PM" src="https://user-images.githubusercontent.com/53093550/70277665-cebd8100-1780-11ea-80ea-3dd42afd72bb.png">

At small breakpoints (672 and below) the L1 is 48px height, not 80px. This is to keep all that good screen real estate free for small screens.

And to answer your question **yes** – the side menu at small breakpoints should be below the overlay:

<img width="742" alt="Screen Shot 2019-12-05 at 4 57 15 PM" src="https://user-images.githubusercontent.com/53093550/70278525-712a3400-1782-11ea-9cc9-88b0b69a836f.png">


—

2. I had the same question and I think it would be more clear to label it something different. I like `Sub-link 1` or `Sub link 1`. 

—

3. I would favor **not including** short footer if we don't want adopters to use it!

**Comment by larahanlon2** [comment]
@oliviaflory there's something weird happening with L1 title:

<img width="951" alt="Screen Shot 2019-12-05 at 4 01 16 PM" src="https://user-images.githubusercontent.com/53093550/70278769-e433aa80-1782-11ea-9847-94346104b7b2.png">
<img width="445" alt="Screen Shot 2019-12-05 at 4 01 26 PM" src="https://user-images.githubusercontent.com/53093550/70278770-e433aa80-1782-11ea-8f96-016215060106.png">
 
Which leads me to my other question/suggestion: could we label the L1 title `L1 link title` or `Sub-link title`?

**Comment by larahanlon2** [comment]
Do you think we could show **an L0 and L1 title link active state** when both Ls are visible? I know this is a template so the active state isn't really applicable because it's out of context but I think it looks weird without any blue underlines. The purpose of the L1 is to show child/subcontent of the parent/L0 nav links but I'm not sure if that's super obvious:

<img width="919" alt="Screen Shot 2019-12-05 at 5 38 05 PM" src="https://user-images.githubusercontent.com/53093550/70280344-42ae5800-1786-11ea-8c0b-aa2f3cfe70bd.png">

To maybe something like this:
<img width="960" alt="Screen Shot 2019-12-05 at 5 42 56 PM" src="https://user-images.githubusercontent.com/53093550/70280557-b2bcde00-1786-11ea-87f5-c22be18f6d11.png">


Would that work?

**Comment by wonilsuhibm** [comment]
This looks great.

2. agreed

3. Let's not include and distribute the footer symbol case by case, since it will be only a handful of pages (URX and Checkout for now).

A question: was there a reason why the footer was included in separate artboards?
